### ISSUE TITLE
Git error code 128 for GPTQ-for-LLaMa

### ISSUE THREAD

**Issue by JadeGrey** [jllllll/one-click-installers#6]
```
Cloning into 'GPTQ-for-LLaMa'...
remote: Enumerating objects: 868, done.
remote: Counting objects: 100% (154/154), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 868 (delta 139), reused 126 (delta 126), pack-reused 714
Receiving objects: 100% (868/868), 495.34 KiB | 1.74 MiB/s, done.
Resolving deltas: 100% (531/531), done.
fatal: destination path 'GPTQ-for-LLaMa' already exists and is not an empty directory.
Command '. "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/installer_files/conda/etc/profile.d/conda.sh" && conda activate "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/installer_files/env" && git clone https://github.com/WapaMario63/GPTQ-for-LLaMa-ROCm.git GPTQ-for-LLaMa -b rocm' failed with exit status code '128'. Exiting...

```

Ran into this issue after trying to install, this issue only happened recently as before it worked with no problems.

**Comment by JadeGrey** [comment]
Nevermind, used old repo

**Comment by JadeGrey** [comment]
Thought I solved it but ran into another issue after trying again
```
Traceback (most recent call last):
  File "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/text-generation-webui/server.py", line 35, in <module>
    from modules import chat, loaders, presets, shared, training, ui, utils
  File "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/text-generation-webui/modules/chat.py", line 17, in <module>
    from modules.text_generation import (
  File "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/text-generation-webui/modules/text_generation.py", line 22, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/text-generation-webui/modules/models.py", line 10, in <module>
    from accelerate import infer_auto_device_map, init_empty_weights
  File "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/installer_files/env/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/installer_files/env/lib/python3.10/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/installer_files/env/lib/python3.10/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/installer_files/env/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/installer_files/env/lib/python3.10/site-packages/accelerate/utils/bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/installer_files/env/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/installer_files/env/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/installer_files/env/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/installer_files/env/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/installer_files/env/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 120, in run_cuda_setup
    binary_name, cudart_path, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 341, in evaluate_cuda_setup
    cuda_version_string = get_cuda_version()
  File "/home/jade/Downloads/yes/one-click-installers-cross-platform-amd/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 311, in get_cuda_version
    major, minor = map(int, torch.version.cuda.split("."))
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by jllllll** [comment]
You will likely have to change:
`if not torch.cuda.is_available(): return 'libbitsandbytes_cpu.so', None, None, None`
to:
`return 'libbitsandbytes_cpu.so', None, None, None`
under:
`def evaluate_cuda_setup():`
in:
`installer_files/env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py`

Current bitsandbytes code does not account for `torch.cuda.is_available()` returning true for ROCm enabled Torch.

**Comment by JadeGrey** [comment]
Originally had to edit the code to remove `run_cmd("git clone https://github.com/WapaMario63/GPTQ-for-LLaMa-ROCm.git GPTQ-for-LLaMa -b rocm", assert_success=True, environment=True)`

I just commented it out like so:
```
if '+rocm' in torver and sys.platform.startswith("linux"):
        rocm_gptq = run_cmd("python -m pip install https://github.com/jllllll/GPTQ-for-LLaMa-Wheels/raw/Linux-x64/ROCm-5.4.2/quant_cuda-0.0.0-cp310-cp310-linux_x86_64.whl --force-reinstall", environment=True).returncode == 0
        # run_cmd("git clone https://github.com/WapaMario63/GPTQ-for-LLaMa-ROCm.git GPTQ-for-LLaMa -b rocm", assert_success=True, environment=True)
```

I then took your suggestion and it works flawlessly now!

**Comment by JadeGrey** [comment]
Anyways the issue is solved, if you need help with anything in general just message me
